version: "2"
services:
    service-a:
        build: ./service-a
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        ports:
            - "8080:80"
        links:
            - service-b
        labels:
            - com.microsoft.azure.public.port
    service-b:
        build: ./service-b
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        expose:
            - 80
